import { N8N_WEBHOOK_URL } from '$env/static/private';

// This function will now initiate the request to n8n and return the Response object
// The caller (the new +server.ts endpoint) will then handle streaming this response to the client.
export async function initiateStreamedDreamAnalysis(dreamId: string, rawText: string): Promise<Response> {
  if (!N8N_WEBHOOK_URL || N8N_WEBHOOK_URL === 'https://your-n8n-instance.com/webhook/dream-analysis') {
    console.warn('N8N_WEBHOOK_URL is not configured. Returning mock stream response.');
    // For development without n8n, return a mock stream
    const mockStream = new ReadableStream({
      async start(controller) {
        const encoder = new TextEncoder();
        const chunks = [
          { interpretation: 'This is a mock interpretation chunk 1. ' },
          { interpretation: 'This is a mock interpretation chunk 2. ' },
          { interpretation: 'This is a mock interpretation chunk 3. ' },
          { interpretation: 'This is a mock interpretation chunk 4. ' },
          { interpretation: 'This is a mock interpretation chunk 5. ' },
          { interpretation: 'This is a mock interpretation chunk 6. ' },
          { interpretation: 'This is a mock interpretation chunk 7. ' },
          { interpretation: 'This is a mock interpretation chunk 8. ' },
          { interpretation: 'This is a mock interpretation chunk 9. ' },
          { interpretation: 'This is a mock interpretation chunk 10. ' },
          { interpretation: 'This is a mock interpretation chunk 11. ' },
          { interpretation: 'This is a mock interpretation chunk 12. ' },
          { interpretation: 'This is a mock interpretation chunk 13. ' },
          { interpretation: 'This is a mock interpretation chunk 14. ' },
          { interpretation: 'This is a mock interpretation chunk 15. ' },
          { interpretation: 'This is a mock interpretation chunk 16. ' },
          { interpretation: 'This is a mock interpretation chunk 17. ' },
          { interpretation: 'This is a mock interpretation chunk 18. ' },
          { interpretation: 'This is a mock interpretation chunk 19. ' },
          { interpretation: 'This is a mock interpretation chunk 20. ' },
          { interpretation: 'This is a mock interpretation chunk 21. ' },
          { interpretation: 'This is a mock interpretation chunk 22. ' },
          { interpretation: 'This is a mock interpretation chunk 23. ' },
          { interpretation: 'This is a mock interpretation chunk 24. ' },
          { interpretation: 'This is a mock interpretation chunk 25. ' },
          { interpretation: 'This is a mock interpretation chunk 26. ' },
          { interpretation: 'This is a mock interpretation chunk 27. ' },
          { interpretation: 'This is a mock interpretation chunk 28. ' },
          { interpretation: 'This is a mock interpretation chunk 29. ' },
          { interpretation: 'This is a mock interpretation chunk 30. ' },
          { interpretation: 'This is a mock interpretation chunk 31. ' },
          { interpretation: 'This is a mock interpretation chunk 32. ' },
          { interpretation: 'This is a mock interpretation chunk 33. ' },
          { interpretation: 'This is a mock interpretation chunk 34. ' },
          { interpretation: 'This is a mock interpretation chunk 35. ' },
          { interpretation: 'This is a mock interpretation chunk 36. ' },
          { interpretation: 'This is a mock interpretation chunk 37. ' },
          { interpretation: 'This is a mock interpretation chunk 38. ' },
          { interpretation: 'This is a mock interpretation chunk 39. ' },
          { interpretation: 'This is a mock interpretation chunk 40. ' },
          { interpretation: 'This is a mock interpretation chunk 41. ' },
          { interpretation: 'This is a mock interpretation chunk 42. ' },
          { interpretation: 'This is a mock interpretation chunk 43. ' },
          { interpretation: 'This is a mock interpretation chunk 44. ' },
          { interpretation: 'This is a mock interpretation chunk 45. ' },
          { interpretation: 'This is a mock interpretation chunk 46. ' },
          { interpretation: 'This is a mock interpretation chunk 47. ' },
          { interpretation: 'This is a mock interpretation chunk 48. ' },
          { interpretation: 'This is a mock interpretation chunk 49. ' },
          { interpretation: 'This is a mock interpretation chunk 50. ' },
          { interpretation: 'This is a mock interpretation chunk 51. ' },
          { interpretation: 'This is a mock interpretation chunk 52. ' },
          { interpretation: 'This is a mock interpretation chunk 53. ' },
          { interpretation: 'This is a mock interpretation chunk 54. ' },
          { interpretation: 'This is a mock interpretation chunk 55. ' },
          { interpretation: 'This is a mock interpretation chunk 56. ' },
          { interpretation: 'This is a mock interpretation chunk 57. ' },
          { interpretation: 'This is a mock interpretation chunk 58. ' },
          { interpretation: 'This is a mock interpretation chunk 59. ' },
          { interpretation: 'This is a mock interpretation chunk 60. ' },
          { interpretation: 'This is a mock interpretation chunk 61. ' },
          { interpretation: 'This is a mock interpretation chunk 62. ' },
          { interpretation: 'This is a mock interpretation chunk 63. ' },
          { interpretation: 'This is a mock interpretation chunk 64. ' },
          { interpretation: 'This is a mock interpretation chunk 65. ' },
          { interpretation: 'This is a mock interpretation chunk 66. ' },
          { interpretation: 'This is a mock interpretation chunk 67. ' },
          { interpretation: 'This is a mock interpretation chunk 68. ' },
          { interpretation: 'This is a mock interpretation chunk 69. ' },
          { interpretation: 'This is a mock interpretation chunk 70. ' },
          { interpretation: 'This is a mock interpretation chunk 71. ' },
          { interpretation: 'This is a mock interpretation chunk 72. ' },
          { interpretation: 'This is a mock interpretation chunk 73. ' },
          { interpretation: 'This is a mock interpretation chunk 74. ' },
          { interpretation: 'This is a mock interpretation chunk 75. ' },
          { interpretation: 'This is a mock interpretation chunk 76. ' },
          { interpretation: 'This is a mock interpretation chunk 77. ' },
          { interpretation: 'This is a mock interpretation chunk 78. ' },
          { interpretation: 'This is a mock interpretation chunk 79. ' },
          { interpretation: 'This is a mock interpretation chunk 80. ' },
          { interpretation: 'This is a mock interpretation chunk 81. ' },
          { interpretation: 'This is a mock interpretation chunk 82. ' },
          { interpretation: 'This is a mock interpretation chunk 83. ' },
          { interpretation: 'This is a mock interpretation chunk 84. ' },
          { interpretation: 'This is a mock interpretation chunk 85. ' },
          { interpretation: 'This is a mock interpretation chunk 86. ' },
          { interpretation: 'This is a mock interpretation chunk 87. ' },
          { interpretation: 'This is a mock interpretation chunk 88. ' },
          { interpretation: 'This is a mock interpretation chunk 89. ' },
          { interpretation: 'This is a mock interpretation chunk 90. ' },
          { interpretation: 'This is a mock interpretation chunk 91. ' },
          { interpretation: 'This is a mock interpretation chunk 92. ' },
          { interpretation: 'This is a mock interpretation chunk 93. ' },
          { interpretation: 'This is a mock interpretation chunk 94. ' },
          { interpretation: 'This is a mock interpretation chunk 95. ' },
          { interpretation: 'This is a mock interpretation chunk 96. ' },
          { interpretation: 'This is a mock interpretation chunk 97. ' },
          { interpretation: 'This is a mock interpretation chunk 98. ' },
          { interpretation: 'This is a mock interpretation chunk 99. ' },
          { interpretation: 'This is a mock interpretation chunk 100. ' },
          { interpretation: 'This is a mock interpretation chunk 101. ' },
          { interpretation: 'This is a mock interpretation chunk 102. ' },
          { interpretation: 'This is a mock interpretation chunk 103. ' },
          { interpretation: 'This is a mock interpretation chunk 104. ' },
          { interpretation: 'This is a mock interpretation chunk 105. ' },
          { interpretation: 'This is a mock interpretation chunk 106. ' },
          { interpretation: 'This is a mock interpretation chunk 107. ' },
          { interpretation: 'This is a mock interpretation chunk 108. ' },
          { interpretation: 'This is a mock interpretation chunk 109. ' },
          { interpretation: 'This is a mock interpretation chunk 110. ' },
          { interpretation: 'This is a mock interpretation chunk 111. ' },
          { interpretation: 'This is a mock interpretation chunk 112. ' },
          { interpretation: 'This is a mock interpretation chunk 113. ' },
          { interpretation: 'This is a mock interpretation chunk 114. ' },
          { interpretation: 'This is a mock interpretation chunk 115. ' },
          { interpretation: 'This is a mock interpretation chunk 116. ' },
          { interpretation: 'This is a mock interpretation chunk 117. ' },
          { interpretation: 'This is a mock interpretation chunk 118. ' },
          { interpretation: 'This is a mock interpretation chunk 119. ' },
          { interpretation: 'This is a mock interpretation chunk 120. ' },
          { interpretation: 'This is a mock interpretation chunk 121. ' },
          { interpretation: 'This is a mock interpretation chunk 122. ' },
          { interpretation: 'This is a mock interpretation chunk 123. ' },
          { interpretation: 'This is a mock interpretation chunk 124. ' },
          { interpretation: 'This is a mock interpretation chunk 125. ' },
          { interpretation: 'This is a mock interpretation chunk 126. ' },
          { interpretation: 'This is a mock interpretation chunk 127. ' },
          { interpretation: 'This is a mock interpretation chunk 128. ' },
          { interpretation: 'This is a mock interpretation chunk 129. ' },
          { interpretation: 'This is a mock interpretation chunk 130. ' },
          { interpretation: 'This is a mock interpretation chunk 131. ' },
          { interpretation: 'This is a mock interpretation chunk 132. ' },
          { interpretation: 'This is a mock interpretation chunk 133. ' },
          { interpretation: 'This is a mock interpretation chunk 134. ' },
          { interpretation: 'This is a mock interpretation chunk 135. ' },
          { interpretation: 'This is a mock interpretation chunk 136. ' },
          { interpretation: 'This is a mock interpretation chunk 137. ' },
          { interpretation: 'This is a mock interpretation chunk 138. ' },
          { interpretation: 'This is a mock interpretation chunk 139. ' },
          { interpretation: 'This is a mock interpretation chunk 140. ' },
          { interpretation: 'This is a mock interpretation chunk 141. ' },
          { interpretation: 'This is a mock interpretation chunk 142. ' },
          { interpretation: 'This is a mock interpretation chunk 143. ' },
          { interpretation: 'This is a mock interpretation chunk 144. ' },
          { interpretation: 'This is a mock interpretation chunk 145. ' },
          { interpretation: 'This is a mock interpretation chunk 146. ' },
          { interpretation: 'This is a mock interpretation chunk 147. ' },
          { interpretation: 'This is a mock interpretation chunk 148. ' },
          { interpretation: 'This is a mock interpretation chunk 149. ' },
          { interpretation: 'This is a mock interpretation chunk 150. ' },
          { interpretation: 'This is a mock interpretation chunk 151. ' },
          { interpretation: 'This is a mock interpretation chunk 152. ' },
          { interpretation: 'This is a mock interpretation chunk 153. ' },
          { interpretation: 'This is a mock interpretation chunk 154. ' },
          { interpretation: 'This is a mock interpretation chunk 155. ' },
          { interpretation: 'This is a mock interpretation chunk 156. ' },
          { interpretation: 'This is a mock interpretation chunk 157. ' },
          { interpretation: 'This is a mock interpretation chunk 158. ' },
          { interpretation: 'This is a mock interpretation chunk 159. ' },
          { interpretation: 'This is a mock interpretation chunk 160. ' },
          { interpretation: 'This is a mock interpretation chunk 161. ' },
          { interpretation: 'This is a mock interpretation chunk 162. ' },
          { interpretation: 'This is a mock interpretation chunk 163. ' },
          { interpretation: 'This is a mock interpretation chunk 164. ' },
          { interpretation: 'This is a mock interpretation chunk 165. ' },
          { interpretation: 'This is a mock interpretation chunk 166. ' },
          { interpretation: 'This is a mock interpretation chunk 167. ' },
          { interpretation: 'This is a mock interpretation chunk 168. ' },
          { interpretation: 'This is a mock interpretation chunk 169. ' },
          { interpretation: 'This is a mock interpretation chunk 170. ' },
          { interpretation: 'This is a mock interpretation chunk 171. ' },
          { interpretation: 'This is a mock interpretation chunk 172. ' },
          { interpretation: 'This is a mock interpretation chunk 173. ' },
          { interpretation: 'This is a mock interpretation chunk 174. ' },
          { interpretation: 'This is a mock interpretation chunk 175. ' },
          { interpretation: 'This is a mock interpretation chunk 176. ' },
          { interpretation: 'This is a mock interpretation chunk 177. ' },
          { interpretation: 'This is a mock interpretation chunk 178. ' },
          { interpretation: 'This is a mock interpretation chunk 179. ' },
          { interpretation: 'This is a mock interpretation chunk 180. ' },
          { interpretation: 'This is a mock interpretation chunk 181. ' },
          { interpretation: 'This is a mock interpretation chunk 182. ' },
          { interpretation: 'This is a mock interpretation chunk 183. ' },
          { interpretation: 'This is a mock interpretation chunk 184. ' },
          { interpretation: 'This is a mock interpretation chunk 185. ' },
          { interpretation: 'This is a mock interpretation chunk 186. ' },
          { interpretation: 'This is a mock interpretation chunk 187. ' },
          { interpretation: 'This is a mock interpretation chunk 188. ' },
          { interpretation: 'This is a mock interpretation chunk 189. ' },
          { interpretation: 'This is a mock interpretation chunk 190. ' },
          { interpretation: 'This is a mock interpretation chunk 191. ' },
          { interpretation: 'This is a mock interpretation chunk 192. ' },
          { interpretation: 'This is a mock interpretation chunk 193. ' },
          { interpretation: 'This is a mock interpretation chunk 194. ' },
          { interpretation: 'This is a mock interpretation chunk 195. ' },
          { interpretation: 'This is a mock interpretation chunk 196. ' },
          { interpretation: 'This is a mock interpretation chunk 197. ' },
          { interpretation: 'This is a mock interpretation chunk 198. ' },
          { interpretation: 'This is a mock interpretation chunk 199. ' },
          { interpretation: 'This is a mock interpretation chunk 200. ' },
          { tags: ['mock', 'analysis', 'dream'], final: true } // Final chunk with tags and a 'final' flag
        ];

        for (const chunk of chunks) {
          await new Promise(resolve => setTimeout(resolve, 50)); // Simulate delay
          controller.enqueue(encoder.encode(`data: ${JSON.stringify(chunk)}\n\n`));
        }
        controller.close();
      },
    });

    return new Response(mockStream, {
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
      },
    });
  }

  try {
    const response = await fetch(N8N_WEBHOOK_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ dreamId, rawText })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error(`n8n webhook call failed for dream ${dreamId}: ${response.status} - ${errorText}`);
      throw new Error(`Failed to trigger n8n analysis: ${response.statusText}`);
    }

    // Assuming n8n returns a stream directly
    return response;

  } catch (error) {
    console.error('Error initiating n8n streamed dream analysis:', error);
    throw new Error(`Failed to initiate streamed dream analysis service: ${(error as Error).message}`);
  }
}
