export enum DreamState {
	CREATED = 'CREATED',
	ENRICHING = 'ENRICHING',
	ENRICHING_REVISION = 'ENRICHING_REVISION',
	INTERPRETING = 'INTERPRETING',
	INTERPRETING_REVISION = 'INTERPRETING_REVISION',
	COMPLETED = 'COMPLETED',
	FAILED = 'FAILED'
}

export type StateTransitionEvent =
	| 'USER_ENTERS_TEXT'
	| 'ALL_ENRICHMENT_COMPLETE'
	| 'ENRICHMENT_HARD_FAIL'
	| 'INTERPRETATION_COMPLETE'
	| 'INTERPRETATION_ERROR'
	| 'USER_EDITS_TEXT'
	| 'USER_RETRIES_INTERPRETATION'
	| 'USER_RETRIES_ENRICHMENT'
	| 'MANUAL_FAIL';

/**
* EventType - Central registry of all event names in the system
*/
export enum EventType {
	// Core Pipeline Events
	ENRICHMENT_STARTED = 'ENRICHMENT_STARTED',
	INTERPRETATION_STARTED = 'INTERPRETATION_STARTED',
	INTERPRETATION_CHUNK = 'INTERPRETATION_CHUNK',
	STATE_CHANGED = 'STATE_CHANGED',

	// Actor Completion Events
	TITLE_GENERATION_COMPLETE = 'TitleGenerationActor_COMPLETE',
	TITLE_GENERATION_FAILED = 'TitleGenerationActor_FAILED',
	CONTEXT_GATHERING_COMPLETE = 'ContextGatheringActor_COMPLETE',
	CONTEXT_GATHERING_FAILED = 'ContextGatheringActor_FAILED',
	RELATIONSHIP_COMPLETE = 'RelationshipActor_COMPLETE',
	RELATIONSHIP_FAILED = 'RelationshipActor_FAILED',
	INTERPRETATION_COMPLETE = 'InterpretationActor_COMPLETE',
	INTERPRETATION_FAILED = 'InterpretationActor_FAILED'
}

/**
 * AuditEventType - Types of events recorded in the travel log / audit trail
 */
export enum AuditEventType {
	STARTED = 'STARTED',
	ENRICHED = 'ENRICHED',
	INTERPRETED = 'INTERPRETED',
	EDITED = 'EDITED',
	FAILED = 'FAILED'
}
